server:
  port: 9001

spring:
  # datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sdz
    username: root
    password: root
    maxActive: 20
    initialSize: 1
    maxWait: 60000
  # dubbo
  dubbo:
    application.name: sdz-provider
    registry.address: zookeeper://192.168.88.128:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.cc.sdz

# mybatis
mybatis:
  typeAliasesPackage: com.cc.sdz.*.entity
  mapperLocations: classpath:/com/cc/sdz/mapper/**/*DAO.xml